config/routes.rb
Checkmate::Application.routes.draw do
  root :to => 'home#index'
  resources :users, :only => [:new, :create, :show]
  resources :banks, :only => [:new, :create, :show]
  resources :transactions, :only => [:new, :create]
  get '/show' => 'banks#new_transaction'
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/models/bank.rb
class Bank < ActiveRecord::Base
attr_accessible :name, :balance
belongs_to :user
has_many :transactions


end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
attr_accessible :date, :amt, :to_whom, :deposit, :withdraw
belongs_to :banks
end

app/models/user.rb
class User < ActiveRecord::Base
has_secure_password
attr_accessible :username, :email, :password, :password_confirmation
has_many :banks
validates :username, :email, :presence => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate

  private
  def authenticate
    @auth = User.find(session[:user_id]) if session[:user_id].present?
  end


end

app/controllers/banks_controller.rb
class BanksController < ApplicationController
  def new
    @bank = Bank.new
  end
  def create
    Bank.create(params[:bank])
    @bank = Bank.order(:name)
    @banks = Bank.all
  end
  def show
    @bank = Bank.find(params[:id])
  end
  def new_transaction
    @bank = Bank.find(params[:id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @banks = Bank.all
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end
  def create
    user = User.where(:email => params[:email]).first
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      @auth = User.find(session[:user_id]) if session[:user_id].present?
    else
      session[:user_id] = nil
    end
  end

  def destroy
    session[:user_id] = nil
    @auth = nil
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
  end
  def new
    @transaction = Transaction.new
  end
  def create
    @transaction = Transaction.create(params[:transaction])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
  def new
    @user = User.new
  end
  def create
    @user = User.create(params[:user])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def login_nav
    nav = ""

    if @user.present? && @user.has_subscription?
      nav += "<li>#{link_to('Profile', '#', :class => 'button tiny success')}</li>"
    end

    if @auth.present?
      nav += "<li>#{link_to(@auth.username, '/login', :method => :delete, :remote => true, :class => 'button tiny alert')}</li>"
    end

    nav
  end
end

app/views/banks/_banks.html.haml
%table
  %tr
    %th Bank Name
    %th Balance
  - @banks.each do |bank|
    %tr
      %td= link_to(bank.name, bank, :class => 'button tiny radius success')
      %td= bank.balance

app/views/banks/_form.html.haml
.row
  .large-3.columns
    = form_for @bank, :remote => true do |f|
      = f.label :name
      = f.text_field :name, :autofocus => true
      = link_to 'Cancel', '#', :'data-clear-form' => true, :class => 'button tiny radius alert'
      = f.submit 'Save', :class => 'button tiny radius success'
  .large-9.columns

app/views/banks/create.js.erb
$('#banks').empty().append('<%=j render(:partial => 'banks') %>');

app/views/banks/new.js.erb
$('#form').empty().append('<%=j render(:partial => 'form') %>');

app/views/banks/show.html.haml
= @bank.name
%br
%br
= link_to('New Transaction', new_transaction_path, :remote => true, :class => 'button tiny radius')
#form


#Deposits
  %h3 Deposits
  =button_tag('Data', :class => 'button tiny radius')
  =button_tag('Graph', :class => 'button tiny radius')

%h3 Withdrawals
#Withdrawals
  =button_tag('Data', :class => 'button tiny radius')
  =button_tag('Graph', :class => 'button tiny radius')
  =image_tag('one.jpeg')

app/views/home/_anonymous.html.haml
- if @auth.nil?
  =link_to('Log In', '/login', :remote => true)
  =link_to('Sign Up', new_user_path, :remote => true)
- else
  =link_to('New Bank', new_bank_path, :remote => true, :class => 'button tiny raius success')

app/views/home/_banks.html.haml
- if @auth.present?
  %table
    %tr
      %th Bank Name
      %th Balance
    - @banks.each do |bank|
      %tr
        %td= link_to(bank.name, bank, :class => 'button tiny radius success')
        %td= bank.balance

app/views/home/index.html.haml
You are on the home page
#anonymous
  = render(:partial => 'anonymous')
#form
#banks
  = render(:partial => 'banks')

app/views/layouts/_body.html.erb
<div class="row">
  <div class="large-12 columns">
    <%= yield %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="row">
  <div class="large-12 columns"><hr>
    <div class="row">
      <div class="large-6 columns">
        <p></p>
      </div>
      <div class="large-6 columns">
        <ul class="inline-list right">
          <li><a href="http://twitter.com/alexfogg"></a></li>
          <li><a href="http://generalassemb.ly"></a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<div class="row">
  <div class="large-12 columns">
    <div class="nav-bar right">
     <ul class="button-group">
       <li><%= link_to('Home', root_path, :class => 'button tiny') %></li>
       <%== login_nav %>
      </ul>
    </div>
    <h2 class='subheader'>CHECKMATE</h2>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if IE 8]>         <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width" />
  <title>albm</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id='nav'><%= render :partial => 'layouts/nav' %></div>
  <div id='body'><%= render :partial => 'layouts/body' %></div>
  <div id='footer'><%= render :partial => 'layouts/footer' %></div>

  <script>
  $(document).foundation();
  </script>
</body>
</html>

app/views/session/_display.js.erb
$('#nav').empty().append('<%=j render(:partial => 'layouts/nav') %>');
$('#anonymous').empty().append('<%=j render(:partial => 'home/anonymous') %>');
$('#form').empty();

app/views/session/_form.html.haml
.row
  .format
    = form_tag '/login', :remote => true do
      = label_tag :email
      = text_field_tag :email, nil, :autofocus => true
      = label_tag :password
      = password_field_tag :password
      = link_to 'Cancel', '#', :'data-clear-form' => true, :class => 'button tiny radius alert'
      = submit_tag 'Login', :class => 'button radius'

app/views/session/create.js.erb
<% if session[:user_id].present? %>
  <%= render(:partial => 'display') %>
<% else %>
  $('#form').empty().append('<%=j render(:partial => 'form') %>');
<% end %>

app/views/session/destroy.js.erb
<%= render(:partial => 'display') %>

app/views/session/new.js.erb
$('#form').empty();
$('#form').empty().append('<%=j render(:partial => 'form') %>');

app/views/shared/_errors.html.haml
- if object.errors.any?
  %h4
    %small= "Fix the following #{pluralize(object.errors.count, 'error')}:"
  %ol
    - object.errors.full_messages.each do |msg|
      %li
        %small.label.alert.radius= msg

app/views/transactions/_deposits.html.haml
%table
  %tr
    %th Date
    %th Amount
    %th To
  - Transaction.all.each do |transaction|
    %tr
      %td=transaction.date
      %td=transaction.amt
      %td=transaction.to_whom

app/views/transactions/_form.html.haml
.row
  .large-3.columns
    = form_for @transaction, :remote => true do |f|
      = f.label :date
      = f.text_field :date, :autofocus => true
      = f.label :amt
      = f.text_field :amt
      = f.label :to
      = f.text_field :to_whom
      = button_tag :dep
      =button_tag :with
      / = link_to 'Cancel', '#', :'data-clear-form' => true, :class => 'button tiny radius alert'
      = f.submit 'Save', :class => 'button tiny radius success'
  .large-9.columns

app/views/transactions/create.js.erb
$('#form').empty().append('<%=j render(:partial => 'deposits') %>');

app/views/transactions/new.js.erb
$('#form').empty().append('<%=j render(:partial => 'form') %>');

app/views/users/_form.html.haml
.row
  .large-3.columns
    = render(:partial => 'shared/errors', :locals => {:object => @user})
    = form_for @user, :url => users_path, :remote => true do |f|
      = f.label :username
      = f.text_field :username, :autofocus => true
      = f.label :email
      = f.text_field :email
      = f.label :password
      = f.password_field :password
      = f.label :password_confirmation
      = f.password_field :password_confirmation
      = link_to('Cancel', '#', :'data-clear-form' => true, :class => 'button tiny radius alert')
      = f.submit nil, :class => 'button tiny radius success'
  .large-9.columns

app/views/users/create.js.erb
<% if @user.valid? %>
  $('#form').empty().after('<p>You are now a member of checkmate. Congrats!</p>');
  $('#form + p').fadeOut(2000, function(){ $('#form + p').remove(); });
<% else %>
  $('#form').empty().append('<%=j render(:partial => 'form') %>');
<% end %>

app/views/users/new.js.erb
$('#form').empty();
$('#form').append('<%=j render(:partial => 'form') %>');